package model

var Models = []interface{}{
	&SysApi{},
	&SysButton{},
	&SysConfigBackend{},
	&SysConfigFrontend{},
	&SysCron{},
	&SysDept{},
	&SysDeptUser{},
	&SysDict{},
	&SysGenPluginList{},
	&ColumnList{},
	&SysLogLogin{},
	&SysLogOperation{},
	&SysJwtClaims{},
	&SysMenu{},
	&SysNotice{},
	&SysNoticeToUser{},
	&SysRole{},
	&SysRoleApi{},
	&SysRoleButton{},
	&SysRoleMenu{},
	&SysTodo{},
	&GqaModelWithCreatedByAndUpdatedBy{},
	&SysUser{},
	&SysUserOnline{},
	&SysUserRole{},
}
