log:
    path: gqalogs
    filename: gqa-log
    maxSize: 20
    maxBackups: 10
    maxAge: 7
mysql:
    host: 47.116.213.145
    port: 33806
    user: quasar
    password: quasarQpAlZm
    database: share
    maxIdle: 100
    maxOpen: 100
system:
    port: 8888
    successCode: 1
    successMessage: Success
    errorCode: 0
    errorMessage: Failed
    bindError: params verification failed
    genPluginToPath: gqagen/plugins
    genPluginTemplatePath: template/genplugin
    importPath: ./template/import
    exportPath: ./template/export
    templatePath: ./template/template
